# Build frontend
FROM oven/bun:1 as frontend-build
WORKDIR /app
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile
COPY . .
RUN bun run build

# Production nginx
FROM nginx:alpine
COPY --from=frontend-build /app/dist /usr/share/nginx/html
COPY deploy/dev/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
