-- Migration for PK battle feature
create table if not exists pk_battles (
  battle_id bigint generated by default as identity primary key,
  creator_a_id bigint,
  creator_b_id bigint,
  start_at timestamptz,
  end_at timestamptz,
  status text,
  score_a integer default 0,
  score_b integer default 0
);

create table if not exists pk_rounds (
  id bigint generated by default as identity primary key,
  battle_id bigint references pk_battles(battle_id),
  creator_a_id bigint,
  creator_b_id bigint,
  start_at timestamptz,
  end_at timestamptz,
  status text,
  score_a integer default 0,
  score_b integer default 0
);

create table if not exists pk_scores (
  id bigint generated by default as identity primary key,
  battle_id bigint references pk_battles(battle_id),
  creator_a_id bigint,
  creator_b_id bigint,
  start_at timestamptz,
  end_at timestamptz,
  status text,
  score_a integer,
  score_b integer,
  created_at timestamptz default now()
);
